# Generated by Django 3.1 on 2020-08-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('text', models.CharField(blank=True, max_length=200, verbose_name='Text FeedBack Form')),
                ('slug', models.CharField(max_length=50, unique=True, verbose_name='slug')),
                ('template', models.CharField(default='pages/feedback_form.html', max_length=100, verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
            },
        ),
    ]
