# Generated by Django 3.1 on 2020-08-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('text', models.TextField(max_length=500, verbose_name='Text')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('template', models.CharField(default='page/index.html', max_length=100, verbose_name='Template')),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Page',
            },
        ),
    ]
