# Generated by Django 3.1 on 2020-08-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('sub_title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sub Title')),
                ('text', models.TextField(max_length=500, verbose_name='Text')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('edit_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Editing')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Publishing')),
                ('published', models.BooleanField(default=True, verbose_name='Publish?')),
                ('template', models.CharField(default='page/post_list.html', max_length=100, verbose_name='Template')),
                ('registration_required', models.BooleanField(default=True, help_text='Only registered users can view this page', verbose_name='Need to be a Sigh Up')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Page',
            },
        ),
    ]
