# Generated by Django 3.1 on 2020-08-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
