# Generated by Django 3.1 on 2020-08-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200820_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(max_length=50, unique=True, verbose_name='slug'),
        ),
    ]
