# Generated by Django 3.1 on 2020-08-19 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', max_length=100, verbose_name='Description')),
                ('template', models.CharField(default='blog/home.html', max_length=500, verbose_name='Template')),
                ('published', models.BooleanField(default=True, verbose_name='Display')),
                ('paginated', models.PositiveIntegerField(default=5, verbose_name='Count Post in Page')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('published', models.BooleanField(default=True, verbose_name='Display or Not?')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Name Post')),
                ('mini_text', models.TextField(max_length=500, verbose_name='Text Post')),
                ('text', models.TextField(max_length=1000, verbose_name='Mini Text')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Date Time')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('edit_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Edit Date')),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Publish Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post/', verbose_name='Main Image')),
                ('template', models.CharField(default='blog/post_detail.html', max_length=500, verbose_name='Template')),
                ('published', models.BooleanField(default=True, verbose_name='Publish')),
                ('status', models.BooleanField(default=False, verbose_name='For Registered')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('viewed', models.PositiveIntegerField(default=0, verbose_name='Viewed')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Category')),
                ('tags', models.ManyToManyField(blank=True, related_name='tag', to='blog.Tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Post',
                'ordering': ['sort', '-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100, verbose_name='Text')),
                ('created_date', models.DateTimeField(auto_now=True, max_length=100, verbose_name='Date Time')),
                ('moderation', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Comment',
            },
        ),
    ]
