# Generated by Django 3.0.8 on 2020-07-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200731_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mini_text',
            field=models.TextField(max_length=500, verbose_name='Text Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Mini Text'),
        ),
    ]
