# Generated by Django 3.0.8 on 2020-07-31 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200731_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Time'),
        ),
    ]
