# Generated by Django 3.1 on 2020-08-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_tag_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='template',
            field=models.CharField(default='blog/post_list.html', max_length=500, verbose_name='Template'),
        ),
    ]
