# Generated by Django 3.1 on 2020-08-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200809_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='template',
            field=models.CharField(default='blog/post_detail.html', max_length=500, verbose_name='Template'),
        ),
    ]
