# Generated by Django 3.1 on 2020-08-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200809_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='template',
        ),
    ]
