# Generated by Django 3.1 on 2020-08-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_tag_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(auto_now=True, max_length=100, verbose_name='Date Time'),
        ),
    ]
