# Generated by Django 3.1 on 2020-08-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200812_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='moderation',
            field=models.BooleanField(default=True),
        ),
    ]
