# Generated by Django 3.1 on 2020-08-12 21:47

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_auth', models.BooleanField(default=False, verbose_name='Is Authenticated')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('title', models.CharField(max_length=100, verbose_name='Name Post')),
                ('status', models.BooleanField(default=False, verbose_name='For Registered')),
                ('is_auth', models.BooleanField(default=False, verbose_name='Is Authenticated')),
                ('anchor', models.CharField(max_length=100, verbose_name='Anchor')),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu', verbose_name='Menu')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitems', verbose_name='Parent Menu')),
            ],
            options={
                'verbose_name': 'Menu Items',
                'verbose_name_plural': 'Menu Items',
            },
        ),
    ]
