# Generated by Django 3.1 on 2020-08-20 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitems',
            old_name='object_od',
            new_name='object_id',
        ),
    ]
