# Generated by Django 3.1 on 2020-08-14 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_auth',
            field=models.BooleanField(default=True, verbose_name='Is Authenticated'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='is_auth',
            field=models.BooleanField(default=True, verbose_name='Is Authenticated'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menu', verbose_name='Menu'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='status',
            field=models.BooleanField(default=True, verbose_name='For Registered'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='url',
            field=models.URLField(max_length=100, verbose_name='URL'),
        ),
    ]
