# Generated by Django 3.1 on 2020-08-20 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('menu', '0002_auto_20200820_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='URL on'),
        ),
    ]
