# Generated by Django 3.1 on 2020-08-20 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitems_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='active',
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu', verbose_name='Menu'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='status',
            field=models.BooleanField(default=False, verbose_name='For Registered'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Name Menu Attribute'),
        ),
    ]
