# Generated by Django 3.1 on 2020-08-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200820_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='anchor',
            field=models.CharField(max_length=100, verbose_name='Anchor'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='url',
            field=models.URLField(max_length=100, verbose_name='URL'),
        ),
    ]
