# Generated by Django 3.1 on 2020-08-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200820_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='anchor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Anchor'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='URL'),
        ),
    ]
